POST http://localhost:8083/courier/
Content-Type: application/json

{
    "parcelId": 3,
    "receiverName": "NANDHANA",
    "parcelItemName": "Tablet",
    "receiverAddress": "789 Lane",
    "receiverContact": 8765432109,
    "itemPrice": 500.00,
    "itemStatus": "transit",
    "executiveName": "Anu"
}


####
PUT http://localhost:8083/courier/
Content-Type: application/json

{
    "parcelId": 1,
    "itemStatus": "delivered"
}

####
GET http://localhost:8083/courier/executive/Hari


###
GET http://localhost:8083/courier/address/543 Gate

####
GET http://localhost:8083/courier/receiver/Harshini


#####
GET http://localhost:8083/courier/




